In [34]:
from scipy.io import loadmat
import numpy as np
import networkx as nx
import sys
import random
from similarity_algorithms import *
from generate_dataset import generate_positive
from process_data import preprocess
%matplotlib inline
lon = loadmat('/home/farid/Downloads/data/DD.mat')

print(len(lon['DD'][0][0][0].todense()))
Z1=lon['DD'][0][0][0].todense()
Z2=lon['DD'][0][0][0].todense()
Z3=lon['DD'][0][0][0].todense()
Z4=lon['DD'][0][0][0].todense()
generate_positive(Z4)

#i defines current row being iterated in a matrix
i = 0
while i < len(Z2):
    #j defines current column being iterated in a matrix. j is always greater than i because we only care about upper half of the Adj matrix
    j = i+1
    #j(column count) should run till last element
    while j < len(Z2):
        random_value = random.randint(0, 1)
        Z2[i, j] = random_value
        #updating lower half of Adj matrix as soon as upper half element is edited
        Z2[j, i] = random_value
        #before exiting a row iteration, this makes sure that the diagonal element is set to 0
        Z2[i, i] = 0
        j+=1
    i+=1

#i defines current row being iterated in a matrix
i = 0
while i < len(Z3):
    #j defines current column being iterated in a matrix. j is always greater than i because we only care about upper half of the Adj matrix
    j = i+1
    #j(column count) should run till last element
    while j < len(Z3):
        random_value = random.randint(0, 1)
        Z3[i, j] = random_value
        #updating lower half of Adj matrix as soon as upper half element is edited
        Z3[j, i] = random_value
        #before exiting a row iteration, this makes sure that the diagonal element is set to 0
        Z3[i, i] = 0
        j+=1
    i+=1



327


In [35]:
Z1

matrix([[0., 1., 1., ..., 0., 0., 0.],
        [1., 0., 1., ..., 0., 0., 0.],
        [1., 1., 0., ..., 0., 0., 0.],
        ...,
        [0., 0., 0., ..., 0., 0., 0.],
        [0., 0., 0., ..., 0., 0., 0.],
        [0., 0., 0., ..., 0., 0., 0.]])

In [36]:
Z2

matrix([[0., 0., 1., ..., 1., 0., 0.],
        [0., 0., 0., ..., 0., 1., 1.],
        [1., 0., 0., ..., 1., 1., 1.],
        ...,
        [1., 0., 1., ..., 0., 1., 1.],
        [0., 1., 1., ..., 1., 0., 0.],
        [0., 1., 1., ..., 1., 0., 0.]])

In [37]:
Z3

matrix([[0., 0., 1., ..., 1., 0., 0.],
        [0., 0., 1., ..., 1., 1., 1.],
        [1., 1., 0., ..., 1., 0., 1.],
        ...,
        [1., 1., 1., ..., 0., 0., 0.],
        [0., 1., 0., ..., 0., 0., 1.],
        [0., 1., 1., ..., 0., 1., 0.]])

In [38]:
Z4

matrix([[0., 0., 0., ..., 0., 0., 0.],
        [0., 0., 0., ..., 0., 0., 0.],
        [0., 0., 0., ..., 0., 0., 0.],
        ...,
        [0., 0., 0., ..., 0., 0., 0.],
        [0., 0., 0., ..., 0., 0., 0.],
        [0., 0., 0., ..., 0., 0., 0.]])

In [42]:
Z1_x = nx.from_numpy_matrix(Z1)
Z2_x = nx.from_numpy_matrix(Z2)
Z3_x = nx.from_numpy_matrix(Z3)

lap1=nx.spectrum.laplacian_spectrum(Z1_x)
lap2=nx.spectrum.laplacian_spectrum(Z2_x)
lap3=nx.spectrum.laplacian_spectrum(Z3_x)

from scipy import spatial
1 - manhattan_distance(lap1,lap2)

0.9849918906982685